-- Migration: 0010_create_user_profiles.sql
CREATE TABLE IF NOT EXISTS `pt_user_profiles` (
  `user_id` BIGINT UNSIGNED NOT NULL,
  `timezone` VARCHAR(50) DEFAULT NULL,
  `locale` VARCHAR(10) DEFAULT NULL,
  `meta` JSON DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_pt_user_profiles_user` FOREIGN KEY (`user_id`) REFERENCES `ids_users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
