-- database/migrations/0028_add_page_group_id_to_pt_menu_items.sql
--
-- No-Op-Migration.
--
-- Im aktuellen Branch reset/base-skeleton wird pt_menu_items.page_group_id
-- bereits in folgender Migration angelegt:
--
-- database/migrations/0018_create_pt_menu_items.sql
--
-- Dort sind bereits vorhanden:
--
-- - pt_menu_items.page_group_id
-- - Index auf page_group_id
-- - Foreign Key auf pt_page_groups
--
-- Diese Migration bleibt nur bestehen, damit die Migrationsnummer 0028
-- in der Historie erhalten bleibt.
--
-- Wichtig:
--
-- Keine PREPARE/EXECUTE/DEALLOCATE PREPARE Statements verwenden.
-- Keine SELECT Statements verwenden.
--
-- Grund:
--
-- Der aktuelle Migration-Runner verarbeitet keine offenen Resultsets aus
-- dynamischem SQL. Dadurch entsteht sonst:
--
-- SQLSTATE[HY000]: General error: 2014
-- Cannot execute queries while other unbuffered queries are active.
--
-- Dieses SET ist ein sicheres No-Op Statement ohne Resultset.

SET @portal_migration_0028_noop = 1;